node: 0
server:
  http:
    address: localhost:8100
    timeout: 5000
  grpc:
    address: localhost:9100
    timeout: 5000
data:
  database:
    driver: postgres
    host: localhost
    port: 5432
    username: postgres
    password: 1234
    db: admin
  cache:
    driver: redis
    host: 127.0.0.1
    port: 6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  etcd:
    schema: http
    host: localhost
    port: 2379
system:
  # 是否跳过激活系统，默认false。如果跳过，所有用户创建后将自动激活。
  skip_activate: false 
  init:
    # 是否初始化系统
    auto_init: true
    tenant_name: "系统"
    tenant_owner_id: 0
    root_dept_name: "总公司"
    root_name: "admin"
    root_password: "Admin@2026"
    root_full_name: "系统管理员"

